public void testDimensionCheck() {
        try {
            TestProblem1 pb = new TestProblem1();
            new ClassicalRungeKuttaIntegrator(0.01).integrate(pb, 0.0, new double[pb.getDimension() + 10], 1.0, new double[pb.getDimension() + 10]);
            Assert.fail("an exception should have been thrown");
        } catch (DerivativeException de) {
            Assert.fail("wrong exception caught");
        } catch (IntegratorException ie) {
        }
    }